# Generated by Django 5.2.17 on 2026-09-04 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_file", models.CharField(max_length=255)),
                ("input_path", models.CharField(max_length=1024)),
                ("xtf_path", models.CharField(blank=True, default="", max_length=1024)),
                ("nav_path", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "detection_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ping_id", models.CharField(blank=True, default="", max_length=255)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("class_label", models.CharField(max_length=64)),
                ("confidence_score", models.FloatField()),
                ("bounding_geometry", models.JSONField(default=dict)),
                ("across_track_m", models.FloatField(blank=True, null=True)),
                ("side", models.CharField(blank=True, default="", max_length=12)),
                (
                    "review_status",
                    models.CharField(default="pending_review", max_length=24),
                ),
                (
                    "source_file",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="detections.detectionjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("actor", models.CharField(blank=True, default="", max_length=128)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "detection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit",
                        to="detections.detection",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit",
                        to="detections.detectionjob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["job", "review_status"], name="detections__job_id_358978_idx"
            ),
        ),
    ]
